# Generated by Django 3.2.3 on 2021-05-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='vote_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_count',
        ),
    ]
